### ISSUE TITLE
Kali sources.list Repositories

### ISSUE THREAD

**Issue by Iridiumflash** [kramse/kramse-labs#1]
The full 'Kali Linux 64 Bit' image your are referring to, has commented out all entries in the sources.list file for apt-get (/etc/apt/sources.list). Running apt-get for updating after installation do absolutely nothing!
The following line should be added to the sources.list:
`deb http://http.kali.org/kali kali-rolling main contrib non-free`
See
 [https://docs.kali.org/general-use/kali-linux-sources-list-repositories](url)

**Comment by kramse** [comment]
Thanks for taking the time to create an issue. I downloaded the image and did an install.

The image:
MD5 (kali-linux-2018.2-amd64.iso) = 95a0b9b6a0b1a25ecb7db4a5029396e4

During installation I accepted the default of using a network mirror.

"Configure the package manager"
Make sure the default "Use a network mirror?" is set to <Yes>

With this, I get sources.list with the content you mention. So I will add this as an instruction! Thanks!
<img width="912" alt="screen shot 2018-06-08 at 12 20 49" src="https://user-images.githubusercontent.com/1912826/41153509-23274c0c-6b17-11e8-80f6-e7a0acfa0c23.png">
<img width="912" alt="screen shot 2018-06-08 at 12 26 04" src="https://user-images.githubusercontent.com/1912826/41153518-2bac5eb2-6b17-11e8-834f-fb762c4e3b9d.png">
